config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  resources :users
  root "products#index"
  get "/:page", to: "static_pages#show"
  resources :products
  resources :suggest_products
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= t ".the" %> <a href="http://www.railstutorial.org/"><%= t ".f_shop" %></a>
  <%= t ".by" %> <a href="http://www.michaelhartl.com/"><%= t ".author" %></a>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only"><%= t ".toggle_navigation" %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <img class= "img-responsive" src="http://framgia.co.jp/images/logo_f.png"
          alt="" class="img-responsive">
          <p class="logo_f"><%= t ".framgia" %></p>
      </a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="navc"><%= link_to t(".suggest"), new_suggest_product_path %></li>
        <li class="navc"><%= link_to t(".help"), "/help" %></li>
        <li class="navc"><%= link_to t(".about"), "/about" %></li>
        <li class="navc"><%= link_to t(".contact"), "/contact" %></li>
        <% if logged_in? %>
          <li class="dropdown navc">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t(".account") %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="navc"><%= link_to t(".login"), login_path %></li>
        <% end %>
        <li class="navc"><%= link_to t(".signup"), signup_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "ecomerces" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: :all,
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
  <div id="fb-root"></div>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>